kind: pipeline
type: docker
name: timestamp

platform: {os: linux, arch: amd64}

steps:
  - name: timestamp
    image: library/alpine
    commands:
      - mkdir -p _output
      - date --utc +%Y%m%d%H%M%S > _output/.timestamp
---
kind: pipeline
type: docker
name: centos-8.4.2105-amd64

platform: {os: linux, arch: amd64}

depends_on:
  - timestamp

steps:
  - name: build-libvirt
    image: appleboy/drone-packer
    settings:
      template: distros/centos
      actions:
        - validate
        - build
      parallel: false
      debug: true
      vars:
        iso_version: 8.4.2105
        iso_edition: Minimal
        provider: libvirt

  - name: build-virtualbox
    image: appleboy/drone-packer
    settings:
      template: distros/centos
      actions:
        - validate
        - build
      parallel: false
      vars:
        iso_version: 8.4.2105
        iso_edition: Minimal
        provider: virtualbox

  - name: build-vmware
    image: appleboy/drone-packer
    settings:
      template: distros/centos
      actions:
        - validate
        - build
      parallel: false
      vars:
        iso_version: 8.4.2105
        iso_edition: Minimal
        provider: vmware
...
