# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#   config.ssh.username = 'vagrant'
#   config.ssh.password = 'vagrant'
  config.vm.box = 'test/microos/20211006201329.4'

  config.vm.provider :libvirt do |v, o|
    o.vm.box_url = "../../../_output/20211006201329/microos/16/amd64/microos-v16.0.0.x86_64-dvd.libvirt.box"
    v.memory = "2048"
    v.cpus = 2
  end

  config.vm.provider :virtualbox do |v, o|
    o.vm.box_url = "../../../_output/20211006201329/microos/16/amd64/microos-v16.0.0.x86_64-dvd.virtualbox.box"
    v.memory = "2048"
    v.cpus = 2
  end

  config.vm.provider :vmware_desktop do |v, o|
    o.vm.box_url = "../../../_output/20211006201329/microos/16/amd64/microos-v16.0.0.x86_64-dvd.vmware.box"
    v.memory = "2048"
    v.cpus = 2
  end

  config.vm.synced_folder '.', '/vagrant', type: 'rsync', disabled: false
end
